[2025-09-06T00:58:49.027+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_insert_select.create_table_clean manual__2025-09-06T00:58:39.112989+00:00 [queued]>
[2025-09-06T00:58:49.045+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_insert_select.create_table_clean manual__2025-09-06T00:58:39.112989+00:00 [queued]>
[2025-09-06T00:58:49.046+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-09-06T00:58:49.075+0000] {taskinstance.py:1350} INFO - Executing <Task(MySqlOperator): create_table_clean> on 2025-09-06 00:58:39.112989+00:00
[2025-09-06T00:58:49.090+0000] {standard_task_runner.py:57} INFO - Started process 4487 to run task
[2025-09-06T00:58:49.103+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'mysql_insert_select', 'create_table_clean', 'manual__2025-09-06T00:58:39.112989+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/crea_tablas.py', '--cfg-path', '/tmp/tmpffepbvmn']
[2025-09-06T00:58:49.108+0000] {standard_task_runner.py:85} INFO - Job 57: Subtask create_table_clean
[2025-09-06T00:58:49.183+0000] {task_command.py:410} INFO - Running <TaskInstance: mysql_insert_select.create_table_clean manual__2025-09-06T00:58:39.112989+00:00 [running]> on host 72c5ffe25b48
[2025-09-06T00:58:49.345+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_insert_select' AIRFLOW_CTX_TASK_ID='create_table_clean' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T00:58:39.112989+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-06T00:58:39.112989+00:00'
[2025-09-06T00:58:49.346+0000] {sql.py:262} INFO - Executing:  CREATE TABLE penguins_clean (
    species INT,
    bill_length_mm DOUBLE,
    bill_depth_mm DOUBLE,
    flipper_length_mm DOUBLE,
    body_mass_g DOUBLE,
    year INT,
    island_Biscoe INT,
    island_Dream INT,
    island_Torgersen INT,
    sex_female INT,
    sex_male INT
        );      
        
[2025-09-06T00:58:49.361+0000] {base.py:73} INFO - Using connection ID 'mysql_conn' for task execution.
[2025-09-06T00:58:49.444+0000] {base.py:73} INFO - Using connection ID 'mysql_conn' for task execution.
[2025-09-06T00:58:49.459+0000] {sql.py:375} INFO - Running statement:  CREATE TABLE penguins_clean (
    species INT,
    bill_length_mm DOUBLE,
    bill_depth_mm DOUBLE,
    flipper_length_mm DOUBLE,
    body_mass_g DOUBLE,
    year INT,
    island_Biscoe INT,
    island_Dream INT,
    island_Torgersen INT,
    sex_female INT,
    sex_male INT
        );      
        , parameters: None
[2025-09-06T00:58:49.461+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 274, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1050, "Table 'penguins_clean' already exists")
[2025-09-06T00:58:49.479+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=mysql_insert_select, task_id=create_table_clean, execution_date=20250906T005839, start_date=20250906T005849, end_date=20250906T005849
[2025-09-06T00:58:49.495+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 57 for task create_table_clean ((1050, "Table 'penguins_clean' already exists"); 4487)
[2025-09-06T00:58:49.509+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-09-06T00:58:49.549+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
