[2025-09-06T02:45:39.389+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_insert_select.wait_for_model_file manual__2025-09-06T02:45:22.252104+00:00 [queued]>
[2025-09-06T02:45:39.403+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_insert_select.wait_for_model_file manual__2025-09-06T02:45:22.252104+00:00 [queued]>
[2025-09-06T02:45:39.403+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-09-06T02:45:39.422+0000] {taskinstance.py:1350} INFO - Executing <Task(FileSensor): wait_for_model_file> on 2025-09-06 02:45:22.252104+00:00
[2025-09-06T02:45:39.434+0000] {standard_task_runner.py:57} INFO - Started process 799 to run task
[2025-09-06T02:45:39.445+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'mysql_insert_select', 'wait_for_model_file', 'manual__2025-09-06T02:45:22.252104+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/crea_tablas.py', '--cfg-path', '/tmp/tmpxr1ct9as']
[2025-09-06T02:45:39.449+0000] {standard_task_runner.py:85} INFO - Job 142: Subtask wait_for_model_file
[2025-09-06T02:45:39.548+0000] {task_command.py:410} INFO - Running <TaskInstance: mysql_insert_select.wait_for_model_file manual__2025-09-06T02:45:22.252104+00:00 [running]> on host ded74915b8e2
[2025-09-06T02:45:39.740+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_insert_select' AIRFLOW_CTX_TASK_ID='wait_for_model_file' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T02:45:22.252104+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-06T02:45:22.252104+00:00'
[2025-09-06T02:45:39.755+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2025-09-06T02:45:39.755+0000] {filesystem.py:64} INFO - Poking for file /opt/***/dags/models/RandomForestclassifier.pkl
[2025-09-06T02:46:09.801+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2025-09-06T02:46:09.804+0000] {filesystem.py:64} INFO - Poking for file /opt/***/dags/models/RandomForestclassifier.pkl
[2025-09-06T02:46:39.841+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2025-09-06T02:46:39.842+0000] {filesystem.py:64} INFO - Poking for file /opt/***/dags/models/RandomForestclassifier.pkl
[2025-09-06T02:47:09.891+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2025-09-06T02:47:09.892+0000] {filesystem.py:64} INFO - Poking for file /opt/***/dags/models/RandomForestclassifier.pkl
[2025-09-06T02:47:39.934+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2025-09-06T02:47:39.936+0000] {filesystem.py:64} INFO - Poking for file /opt/***/dags/models/RandomForestclassifier.pkl
[2025-09-06T02:48:09.979+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2025-09-06T02:48:09.979+0000] {filesystem.py:64} INFO - Poking for file /opt/***/dags/models/RandomForestclassifier.pkl
[2025-09-06T02:48:40.031+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2025-09-06T02:48:40.032+0000] {filesystem.py:64} INFO - Poking for file /opt/***/dags/models/RandomForestclassifier.pkl
[2025-09-06T02:49:10.069+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2025-09-06T02:49:10.070+0000] {filesystem.py:64} INFO - Poking for file /opt/***/dags/models/RandomForestclassifier.pkl
[2025-09-06T02:49:40.098+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2025-09-06T02:49:40.100+0000] {filesystem.py:64} INFO - Poking for file /opt/***/dags/models/RandomForestclassifier.pkl
[2025-09-06T02:50:10.151+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2025-09-06T02:50:10.152+0000] {filesystem.py:64} INFO - Poking for file /opt/***/dags/models/RandomForestclassifier.pkl
[2025-09-06T02:50:40.193+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2025-09-06T02:50:40.193+0000] {filesystem.py:64} INFO - Poking for file /opt/***/dags/models/RandomForestclassifier.pkl
[2025-09-06T02:51:10.232+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2025-09-06T02:51:10.234+0000] {filesystem.py:64} INFO - Poking for file /opt/***/dags/models/RandomForestclassifier.pkl
[2025-09-06T02:51:40.275+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2025-09-06T02:51:40.278+0000] {filesystem.py:64} INFO - Poking for file /opt/***/dags/models/RandomForestclassifier.pkl
[2025-09-06T02:51:53.581+0000] {local_task_job_runner.py:299} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2025-09-06T02:51:53.583+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 799. PIDs of all processes in the group: [799]
[2025-09-06T02:51:53.583+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 799
[2025-09-06T02:51:53.584+0000] {taskinstance.py:1540} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-09-06T02:51:53.614+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 253, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1542, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-09-06T02:51:53.621+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=mysql_insert_select, task_id=wait_for_model_file, execution_date=20250906T024522, start_date=20250906T024539, end_date=20250906T025153
[2025-09-06T02:51:53.648+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 142 for task wait_for_model_file (Task received SIGTERM signal; 799)
[2025-09-06T02:51:53.677+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=799, status='terminated', exitcode=1, started='02:45:38') (799) terminated with exit code 1
